// examples/react/src/Counter.tsx
import { useState } from 'react';

interface CounterProps {
  initialCount?: number;
}

const Counter = ({ initialCount = 0 }: CounterProps) => {
  const [count, setCount] = useState(initialCount);

  return (
    <div>
      <span data-testid="count">Count: {count}</span>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        Increment
      </button>
    </div>
  );
};

export default Counter;

// examples/vue/src/Counter.tsx
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'CounterJsx',

  props: {
    initialCount: {
      type: Number,
      default: 0,
    },
  },

  emits: ['increment'],

  setup(props, { emit }) {
    const count = ref(props.initialCount);

    const increment = () => {
      count.value++;
      emit('increment', count.value);
    };

    return () => (
      <div>
        <span data-testid="count">Count: {count.value}</span>
        <button type="button" onClick={increment}>
          Increment
        </button>
      </div>
    );
  },
});
