// examples/browser-react/src/Counter.tsx
import { useState } from 'react';
import './Counter.css';

interface CounterProps {
  initialCount?: number;
}

export function Counter({ initialCount = 0 }: CounterProps) {
  const [count, setCount] = useState(initialCount);

  return (
    <div className="count">
      <span data-testid="count">{count}</span>
      <button
        type="button"
        className="count-btn"
        onClick={() => setCount((c) => c + 1)}
      >
        Increment
      </button>
      <button
        type="button"
        className="count-btn"
        onClick={() => setCount((c) => c - 1)}
      >
        Decrement
      </button>
    </div>
  );
}

// examples/svelte-rsbuild/src/components/Counter.svelte
<script lang="ts">
import { getDefaultStep } from '@/utils/step';

export let initialValue = 0;
export let step = getDefaultStep();

let count = initialValue;

function decrement() {
  count -= step;
}

function increment() {
  count += step;
}

function reset() {
  count = initialValue;
}
</script>

<div data-testid="counter">
  <button type="button" on:click={decrement} data-testid="decrement-btn">-</button>
  <span data-testid="counter-value">{count}</span>
  <button type="button" on:click={increment} data-testid="increment-btn">+</button>
  <button type="button" on:click={reset} data-testid="reset-btn">Reset</button>
</div>
